GlotPress/gp-translation-helpers

- helpers/helper-translation-discussion.php
This pull request addresses the issue of commenters posting invalid or non-existent locales or transaction IDs along with their comments. I have added the the 'sanitize_callback' function that checks this and handles invalid inputs.
> Add sanitize callback to comment meta registration

- helpers-assets/templates/translation-discussion-comments.php
I added an asterisk (*) to show that the comment topic field is required before a comment can be submitted. See screenshot below;
> Add asterisk to show that the Topic dropdown is required

- helpers/helper-translation-discussion.php
Comments are already shown in a threaded view so there's no need to have the 'in reply to' link which is also broken.
> Remove broken 'in reply to' link

- helpers/helper-translation-discussion.php
- includes/class-gp-route-translation-helpers.php
- includes/class-gp-translation-helpers.php
Before this, the permalinks for the comments page (visible in wp-admin/edit-comments.php or permalinks generated on the comment page) had the format `/gth_original/123` instead of the page for the original (`/projects/$project_path/$original_id/`).
This implements a filter that makes WordPress generate the correct permalinks so that it's now possible to view the comments from wp-admin in the context of the original page.
Before:
After:
> Generate a valid original permalink for the custom post type

- helpers/helper-translation-discussion.php
#15 broke starting a new discussion on a original that didn't have a shadow post. See the report at https://make.wordpress.org/polyglots/2022/02/08/call-for-early-testers-glotpress-feedback-feature/#comment-293842
This attempts to fix this.
> Fix broken new discussion

- js/reject-feedback.js
Add the line `$gp.editor.set_status( button, status );` so that when the `Reject` button is clicked, the translation status can be set even though rejection reasons and rejection comment are both empty. 
This also prevents posting empty rejection feedback and comments via AJAX.
> Set translation status

- helpers/helper-translation-discussion.php
When the discussion doesn't have a translation, the translation_id is empty, so the type of the received value in the sanitize_translation_id function is string
> Discussion doesn't have a translation

- includes/class-gp-route-translation-helpers.php
- templates/original-permalink.php
For this original https://glotpress.local/projects/wp-plugins/ultimate-tinymce/dev/726407/de/default/
the original permalink is displayed like this:
This changes the escaping function to `esc_translation()` to not mangle the escaped HTML tags:
This also adds a link below the original to allow entering a translation (if viewed on an original page with locale)
> Improve the original display

- includes/class-gp-route-translation-helpers.php
We've got a few problems with the original permalink URLs:
- We get a fatal error if the original id doesn't exist.
- We load the page even if the project path is wrong.
- Fatal fixed.
- We redirect to the correct project path for the original id.
> Improve URL robustness

- helpers-assets/js/translation-discussion.js
Posting a comment on a discussion page should be added to the top of the comments without a page reload. 
However, it was discovered that when there's no current translation(which means translation_id is null or undefined), a page reload (after posting a comment) is required for the comment to be displayed - this has been fixed in this PR.
In this PR, if the `translation_id` sent via ajax when posting comment is null or undefined, we set it to `0`
> Fix null/undefined translation_id

- includes/class-gp-translation-helpers.php
Before, when a bulk rejection is done and a feedback added, it shows the comment author as anonymous on the discussions tab even though the user is logged in. This is due to missing `user_id` parameter for the `wp_insert_comment` function.
This PR adds the current user_id to the comment data submitted when doing a bulk rejection.
> Add current user_id to comment data

- templates/original-permalink.php
Issue: Linking to the exact comment with e.g  #comment-123 in the url is currently broken and this is due to loading the content via AJAX.
This PR fixes the above issue by loading the comments template  as a child of `<div class="async-content">` on page load, instead of loading empty `<div class="async-content"></div>` for the discussions tab.
> Load discussion tab inline without AJAX

- helpers/helper-translation-discussion.php
- includes/class-gp-translation-helpers.php
- js/reject-feedback.js
Before now, list of reject reasons are manually added to the rejection forms in the frontend.
This PR allows us fetch list of reject reasons from the backend and this also allows easy updating of the reasons without having to make changes in several parts of the code.
> Load reject reasons from backend

- js/reject-feedback.js
This PR fixes the bug where the reject button doesn't work when there's no comment entered or reason selected.
Now, you can reject a single translation without having to enter any feedback.
> Reject when both reason and comment are empty

- helpers-assets/js/translation-discussion.js
Disable all the "Post Comment" buttons when the user clicks on it, so we avoid having multiple requests. I disable another "Post Comment" buttons, so we avoid sending a new post comment request when another one is being processed.
> Disable all the comment buttons when the user clicks on it

- includes/class-gp-translation-helpers.php
- js/reject-feedback.js
When using the normal GlotPress templates, `thickbox` doesn't open because of a couple of missing dependencies.
> GlotPress Core Templates: Bulk Reject doesn't open Thickbox dialog

- helpers-assets/css/translation-discussion.css
- includes/class-gp-translation-helpers.php
When we create a comment with a bulk/give feedback rejection, some fields are empty.
This creates some problems, like in the notifications, because we don't have an email address to send the emails. This PR adds the missing fields in the comment.
- comment_author
- comment_author_email
- comment_author_url
- comment_author_IP
- comment_agent
> Add comment fields

- js/reject-feedback.js
When trying to do a bulk rejection a GlotPress template environment, the `Reject` button in the popover does not work when clicked in GlotPress template. This PR fixes the issue by modifying the jQuery selector used.
The button selector used in jQuery has been modified to use the ID  attribute of the reject button.
Please follow the steps indicated in the screenshot to test on the `main` branch to reproduce the problem and on the `glotpress-reject-btn` to see the solution.
For the solution, the page will be reloaded and a notice displayed as seen below;
> GP Template: Fix jQuery selector for 'Reject' button on popover 

- includes/class-gp-translation-helpers.php
- js/reject-feedback.js
When you try to reject strings that have no translations, the ajax call on clicking the "Reject" button on the popover returns a 500 error
Check that the strings have a translation before making the ajax call, otherwise if they have no translation(s), submit the form with empty values and the default message e.g "0 translations were rejected" will be displayed.
To reproduce the issue, do a git checkout to the `main` branch and follow the steps below;
> For a project, use the "Untranslated' filter as shown below;
>Then select a couple of untranslated strings and choose "Reject" in the action dropdown and click "Apply". 
>Fill the form that shows on the popover and click "Reject". You would see the error in the browser console.
To test the solution go a git checkout to the …
> Check for empty translationIds before bulk rejection

- helpers/helper-translation-discussion.php
The link to the user profile is incorrect, because we are using the `$comment_author` in the URL.
Remove the filter that was causing the problem.
Push the mouse over the link to check that the new URL is correct. Click on the link to go to the user profile.
> Correct the user's URL

- includes/class-wporg-notifications.php
There's a typo that caused this error  E_ERROR: Uncaught Error: Function name must be a string in /home/wporg/public_html/wp-content/plugins/gp-translation-helpers/includes/class-wporg-notifications.php:195
In this PR, I have removed the `$` sign causing the error
> Fix typo causing PHP error

- js/reject-feedback.js
The popover for bulk reject is only shown if one or more strings selected is a current translation. If all strings selected are either waiting/fuzzy translations or does not contain at least one current translation, the popover doesn't display rather it throws an error "No translations were supplied".
**translate.wordpress.org**
**Local GlotPress install**
Here's is how it's been fixed In this PR, when multiple strings are selected in a bulk selection each selected string is checked if it's not untranslated and then it's added to the array of selected strings.
Choose any of these filter options and try to do a bulk reject
The popover won't show up if the filter option is `untranslated` or if all the strings selected are untranslated.
> Don't show popover  only if all selected strings are not untranslated

- includes/class-gp-notifications.php
- includes/class-gp-translation-helpers.php
When a validator rejects one or several strings, the plugin didn't send a notification to the translator.
This PR sends a notification to the translator when one or several strings are rejected.
Add some translations with one user (user 1).
Reject one translation with a different user (user 2).
The translator (user 1) will get a notification.
Reject some translations in a bulk translation (user 2).
The translator (user 1) will get a notification with 2 URL, without the original and translation strings, because in this situation we have two or more strings.
> Notification on rejection

- helpers-assets/templates/translation-discussion-comments.php
- helpers/helper-translation-discussion.php
Some users can't correctly tell what `*` means. Hence, we need to add a short note (e.g 'Required') beside the `*` explaining what we mean by adding `*` to the form labels.
In this PR I have added a text 'required' to the labels of required fields. Here's how it now looks, see below;
> Add '(required)' to comment required form labels

- css/discussion.css
- helpers/helper-translation-discussion.php
- includes/class-gp-translation-helpers.php
- js/reject-feedback.js
- js/translation-helpers.js
- templates/translation-row-editor-meta-feedback.php
When you are rejecting a string, the reject reasons don't have an explanation. This PR proposes to add a tooltip with explanation for Reject Reasons.
Solves https://github.com/GlotPress/gp-translation-helpers/issues/81.
This PR adds tooltips to the rejection reason, using an array with a description for each rejection reason, both in the individual rejection (sidebar) and in the bulk rejection (popover). See next screenshots.
You need to test it manually:
* Single rejection. Go to "Give feedback" in the sidebar and put the mouse over a reject reason. You will see the tooltip with the explanation.
* Bulk rejection. Reject some translations with the bulk functionality. You will get a popover. Put the mouse over a reject reason. You will see the tooltip with the explanation.
> Add the tooltips to the reject reasons

- css/discussion.css
- helpers/helper-translation-discussion.php
Reply link on the discussions page was not conspicuous enough. See how it looked below;
Added css classes `button` and `is-primary` to the reply link and it now looks like this, see below;
> Add button style to reply link

- js/reject-feedback.js
This PR fixes https://github.com/GlotPress/gp-translation-helpers/issues/68. When the 'Request with feedback' Ajax request fails, the user doesn't get an error message. 
This PR adds the error message, to inform the user that the error has happened.
To reproduce this error, comment the [nonce in the class-gp-translation-helpers.php](https://github.com/GlotPress/gp-translation-helpers/blob/main/includes/class-gp-translation-helpers.php#L374), so the Ajax request fails due to an incorrect nonce.
Then try to reject a single or bulk translation, and you will see the error.
> Catch the Ajax errors in the reject with feedback

- helpers/helper-translation-discussion.php
The textarea doesn't show up when the reply button is clicked. See screenshot below;
Solves https://github.com/GlotPress/gp-translation-helpers/issues/86.
This PR removes a comment_field in the comment_form, so the textarea is showed in the reply to a comment.
Go to a discussion page and try to reply to a comment. You will see the form with the textarea and the "Post comment" button. Reply to the comment and click in the button to see the reply stored in the database.
> Show the textarea in a reply to a comment

- css/discussion.css
- helpers-assets/templates/translation-discussion-comments.php
- includes/class-gp-translation-helpers.php
- js/reject-feedback.js
Some of the buttons do not conform to the GlotPress button style.
See before and after screenshots below;
Modify styles to make the buttons conform to GlotPress button styles.
> Apply glotpress style to buttons

- templates/translation-row-editor-meta-feedback.php
This PR: 
* Rename "Reason" to "Type (Optional)" since it can also be used for positive comments.
* Rename "Comment" to "Comment (Optional)".
Resolves https://github.com/GlotPress/gp-translation-helpers/issues/89. 
Update the texts:
* "Reason" to "Type (Optional)".
* "Comment" to "Comment (Optional)".
Go to a translation project, open a pending or translated string, and  you will see the new texts.
> Update some texts in the single rejection with feedback

- includes/class-gp-notifications.php
- includes/class-wporg-notifications.php
We need to add a link to the exact comment in the discussions page.
Added anchor tags to the " new comment in a GlotPress discussion" text in the email body.
On a local GlotPress installation, clicking `new comment in a GlotPress discussion` or `new comment in a discussion` on translate.wordpress.org as shown below should redirect to the exact comment on the discussions page.
> Add link to specific comment on the discussions page

- gp-translation-helpers.php
- helpers-assets/templates/translation-discussion-comments.php
- includes/class-wporg-customizations.php
In the select item where we add a new comment in a discussion, we don't show who will receive a notification.
See https://github.com/GlotPress/gp-translation-helpers/issues/71. 
This PR adds info about who will receive the notifications in GlotPress and 3 filters to modify the options in the select item, so we can change it at translate.w.org.
These are the default messages:
These are the messages updates using the hooks:
The PR adds a new class that will update this info at translate.w.org.
Go to a discussion page and try to add a comment. You will see the new messages in the select element. If you want to test the translate.w.org messages without a sandbox, you can [comment this check](https://github.com/GlotPress/gp-translation-helpers/blob/clarify-notifications/includes/class-wporg-cus …
> Update the options in the select item where we add a new comment in a discussion

- helpers/helper-translation-discussion.php
- includes/class-gp-translation-helpers.php
- js/reject-feedback.js
- templates/translation-row-editor-meta-feedback.php
When you add some comments in a single action, if you approve or fuzzy the translation(s), the comment is not stored in the database, and we don't send any notifications.
See https://github.com/GlotPress/gp-translation-helpers/issues/91.
We don't need to update the email template:
We need to:
* Store the comment when the translation is set to approved or fuzzy.
* Update the template discussion, removing some references to "reject" or "rejection", because the comment can be related with other translation state.
* Send the notification to the translator.
This PR doesn't update the bulk rejection, so the users only can make comments in the bulk rejection, not in the bulk approve or bulk fuzzy.
Updates in the discussion template:
* Make some comment in a pending translation.
* Set as approved …
> Allow to add a comment and approve or fuzzy the translation

- js/reject-feedback.js
We have a JS problem when a translator suggests a translation, and then she tries to reject her own translation. See https://github.com/GlotPress/gp-translation-helpers/issues/98.
This solution checks if a textarea is defined, to avoid errors when we try to access to an undefined object.
1. Log in with a non validator user.
2. Suggest a string.
3. Reject your own suggestion.
4. You get the string rejected. Before this PR, in this step, you get an error.
> Check if the comment textarea exists to avoid a JS error

- includes/class-gp-translation-helpers.php
- js/reject-feedback.js
In order to fix this issue -> #97 , we need to be able to tell what the specific error is.
In this PR, I have added an error message to be returned in the ajax call and also show the input data in the console for proper debugging. After this issue has been fixed, the `console.error( data )` will be removed.
When doing a bulk reject with feedback as mentioned in #97, the input data should be displayed in the browser console and a non-generic error message should be shown to the user.
> Bulk Reject: Generate better error

- helpers/helper-translation-discussion.php
- includes/class-gth-temporary-post.php
On WordPress trunk our "hack" for displaying the comment form without an existing (shadow) post no longer works (broken by https://github.com/WordPress/WordPress/commit/1069ac4afda821742cf7f600412aacc139013a55). Thus no comment form is displayed if there is no other discussion. We also want to avoid creating shadow posts just by visiting the page, so that we don't end up with many posts without discussion.
This PR attempts to solve this although only haphazardly so far (by checking for `$post_id === 0`).
Go to a discussion page of an original that doesn't have a discussion yet. The comment form should be visible.
> Fix discussion form not showing in empty discussions

- includes/class-gp-notifications.php
- includes/class-wporg-notifications.php
In the email sent when a translation is rejected, the reason for rejection is not added.
This PR adds the reason for rejection to the body of the email sent when a translation is rejected.
- Suggest a translation as a user
- Reject the translation as another user
- Check the body of email sent and you will see the item "Reason" on the list (see screenshot below)
> Add rejection reasons to email body

- includes/class-wporg-notifications.php
We have some errors with this message:
```
Uncaught TypeError: Argument 1 passed to WPorg_GlotPress_Notifications::is_global_optout_email_address() must be of the type string, null given, called in gp-translation-helpers/includes/class-wporg-notifications.php on line 427 
```
```
Uncaught TypeError: Argument 1 passed to WPorg_GlotPress_Notifications::is_global_optout_email_address() must be of the type string, null given, called in gp-translation-helpers/includes/class-wporg-notifications.php on line 433 and defined in gp-translation-helpers/includes/class-wporg-notifications.php:452
Stack trace:
#0 gp-translation-helpers/includes/class-wporg-notifications.php(433): WPorg_GlotPress_Notifications::is_global_optout_email_address(NULL)
#1 …
```
> is_global_optout_email_address parameter incorrect

- gp-translation-helpers.php
- includes/class-gp-translation-helpers.php
Sometimes when we deploy the plugin to DotOrg, we have problems with the asset versions (CSS and JS), so we need to set a method to version and update the assets each time we deploy to production.
Use the plugin version as asset version. Using this value (and increasing it each time we deploy at DotOrg) we will avoid version problems with the assets.
Load a translation page or a discussion page (in a local GlotPress or at DotOrg) and you will see that the plugin assets (CSS and JS) will have the plugin version as version number (0.0.3 in this example):
`<link rel="stylesheet" id="gp-discussion-css-css" href="https://glotpress.test/wp-content/plugins/gp-translation-helpers/includes/../css/discussion.css?ver=0.0.3" media="all">`
> Add the plugin version in the asset register: CSS and JS

- templates/original-permalink.php
When you visit a discussions page that has no locale in the URL(e.g. https://translate.wordpress.org/projects/wp-plugins/complianz-gdpr/dev-readme/13048945), you find the text "This string has no translation in this language." even if there's already a current/waiting/fuzzy/rejected translation and this is really confusing because when you visit the discussions page with the locale in the URL(e.g https://translate.wordpress.org/projects/wp-plugins/complianz-gdpr/dev-readme/13048945/es/default/) you find out there may be actual translations existing.
Remove the text "This string has no translation in this language." from the discussions page if there's no locale in the discussions page URL
> Before
https://translate.wordpress.org/projects/wp-plugins/complianz-gdpr/dev-readme/13048945
> …
> Don't show `This string has no translation in this language.` if there's no locale in the discussions page URL

- gp-translation-helpers.php
- helpers/helper-translation-discussion.php
- includes/class-gp-notifications.php
- js/reject-feedback.js
- templates/gp-templates-overrides/translation-row-editor-meta-status.php
This PR, with [another one](https://github.com/GlotPress/GlotPress/pull/1451) in the GlotPress plugin, adds a new status: changes requested.
This plugin only send the information with a new status (changes_requested) when:
- A simple rejection is made, adding some feedback.
- A bulk rejection is made, adding some feedback.
To test this PR, you have to use the [related branch](https://github.com/GlotPress/GlotPress/pull/1451) from GlotPress and you have to reject some strings as validator (simple or bulk rejection), adding some feedback.
> Add a new status: changes requested

- helpers-assets/templates/translation-discussion-comments.php
- helpers/helper-translation-discussion.php
- templates/discussions-dashboard.php
#100 introduced two notices:
```
E_NOTICE: Undefined variable: original_permalink in helpers-assets/templates/translation-discussion-comments.php:51
```
and
```
E_NOTICE: Trying to get property 'comment_post_ID' of non-object in templates/discussions-dashboard.php:76
```
This adds more checks to avoid the notices.
> Fix notices introduced in #100

- css/discussion.css
- helpers-assets/templates/translation-discussion-comments.php
It's sometimes confusing when you have multiple comment forms displayed at the same time. This is usually the case when a user clicks on the "Reply" button where a new comment form is displayed in addition to the comment form for new comments.
Hide the comment form for new comments
> Hide new comment form

- helpers-assets/templates/translation-discussion-comments.php
- helpers/helper-translation-discussion.php
- includes/class-gp-route-translation-helpers.php
- includes/class-gp-translation-helpers.php
- js/reject-feedback.js
When you are in the discussion page for an original, you don't get the translation status of the translation related with each comment. 
Fixes #103. 
This PR adds the translation status related with the comment.
For an original string:
* Suggest a translation.
* Reject this suggestion with comment.
* Suggest another different translation.
* Accept this suggestion with comment.
* Go to the discussion page for this original. You will see the translation status of the string related with the comment.
> Add the status of the translation in the discussion

- templates/translation-row-editor-meta-feedback.php
The feedback form is not showed, and the users has to open it to work with it. Some users have request to show it by default. Fixes https://github.com/GlotPress/gp-translation-helpers/issues/119.
Change the `<details>` default visibility, showing the feedback form by default.
Clear the cache, reload the main translation table, open a row with some translation and you will see the feedback form without doing any extra click.
It works fine at translate.w.org.
> Show the feedback form open by default

- css/discussion.css
- templates/translation-row-editor-meta-feedback.php
We don't show to the validators that the feedback will be public, available to all users. 
This PR adds a label with this information.
This is the screenshot at translate.w.org
Reload the browser and clear the cache to see the new text.
> Add info showing to the validators the feedback is public

- css/discussion.css
- js/reject-feedback.js
We are trying to shorten the user journey when rejecting with feedback. As a result, when approver selects "Glossary" as the reason for rejection, we show a list of checkboxes of Glossary items that appear in the original of which the approver can select which of them is wrong for the current translation(s).
Mockup:
We don't store this as additional metadata but generate an English text. It would be interesting to provide a similar hover functionality as in the original text.
> Show dropdown of glossary words extracted from the original

- includes/class-gp-route-translation-helpers.php
- templates/discussions-dashboard.php
Can't filter discussions to identify discussions needing responses.
We'll add the ability to filter discussions based on whether the user has participated in it, not participated by clicking the filter links on top of the table.
> Add list of links for filters

- includes/class-gp-translation-helpers.php
When you do a bulk 'changes requested', the link to the comment which contains the reasons and comments entered during the bulk action is only displayed on the discussions page for the second translation and not for the subsequent ones.
With this PR, only the comment on the discussions page for the first rejected translation displays the full comment, for other rejected translations, a link to the comment for the first translation is displayed.
> Comment for the first rejected translation
> Comment for the second rejected translation
1. Select more than 2 translations that you want to reject.
2. Use the bulk actions dropdown and select 'Reject' and click 'Apply'.
3. Choose a few reasons and enter a comment in the popover displayed and click 'Request changes'.
4. Go to the discussions page …
> Fix broken linked comments for bulk rejection

- css/editor.css
- gp-translation-helpers.php
- includes/class-gp-sidebar.php
- includes/class-gp-translation-helpers.php
- js/editor.js
Currently, if you want to see the discussion for the translation, you have to open it in another page. This page has 3 tabs, with the discussions, the history and the "other languages" translation.
Solves https://github.com/GlotPress/gp-translation-helpers/issues/147.
This PR depends on this https://github.com/GlotPress/GlotPress/pull/1531, because it adds a required filter.
This PR adds 3 tabs, with the discussions, the history and the "other languages" translation.
You need to be on the `tabs-sidebar` branch on the https://github.com/GlotPress/GlotPress/pull/1531 PR, because this PR adds a required filter.
Then you can start working with the content on the 4 tabs:
* Meta. You can work as you usually work on the current tab to test the functionality.
* Discuss. You can create new …
> Add some components to add tabs in the right sidebar

- css/discussion.css
- includes/class-wporg-customizations.php
- templates/discussions-dashboard.php
On the discussions dashboard, we need to GTEs to be able to see the other GTEs involved in a discussion.
Add column titled "GTEs/PTEs/CLPTEs Involved"
> On translate.wordpress.org
> In GlotPress core
Visit the discussions dashboard for a locale and the new column should be present.
> Add GTEs/PTEs Involved column

- helpers/helper-translation-discussion.php
- includes/class-gp-translation-helpers.php
- js/reject-feedback.js
This notice is thrown quite frequently on translate.wordpress.org 
`E_NOTICE: Undefined index: translation_status in /home/wporg/public_html/wp-content/plugins/gp-translation-helpers/includes/class-gp-translation-helpers.php:415`
It's related to this [line](https://github.com/GlotPress/gp-translation-helpers/blob/06418470d081f03dd78c751d28e76e7dbf958940/includes/class-gp-translation-helpers.php#L415)
This notice is thrown when a bulk `changesrequested` action is done. This is because we don't send the translation status of each rejected translation in the payload for bulk rejection.
We add the translation status for each item in the bulk rejection to the payload before sending it via AJAX.
> Fix undefined translation_status notice

- helpers/helper-translation-discussion.php
- includes/class-wporg-notifications.php
E_NOTICE: Undefined index: original_permalink in wp-content/plugins/gp-translation-helpers/helpers/helper-translation-discussion.php:582
E_NOTICE: Trying to get property 'ID' of non-object in wp-content/plugins/gp-translation-helpers/includes/class-wporg-notifications.php:157
E_NOTICE: Trying to get property 'user_nicename' of non-object in wp-content/plugins/gp-translation-helpers/includes/class-wporg-notifications.php:154
These PHP Notices have been constantly being hit on WordPress.org.
This is not a fix. This is a bandaid (mostly).
This is deployed to WordPress.org.
No testing has been done.
> Fix three constant PHP Notices.

- js/reject-feedback.js
When a user makes a multiple selection with the checkbox at the top of the table, and then she made a bulk rejection, the "Reject with Feedback" form was not shown: all the translations are rejected.
The problem is happening with this header checkbox, when we try to get the `translationStatus`, because it fires an exception.
```
if ( ( ! selectedRow.hasClass( 'untranslated' ) ) ) {
translationStatus = selectedRow.attr( 'class' ).split( ' ' )[ 1 ].substring( 7 );
bulkTranslationStatus.push( translationStatus );
return selectedRow.attr( 'row' );
}
```
The solution is to check the `selectRow` length, to be sure the `selectedRow` exists.
1. Apply the PR.
2. Select all the translations in the translation table.
3. You will see the "Reject with Feedback" form in a popup.
> Check if the row selectedRow has length, to avoid the first one in a bulk selection

- css/discussion.css
- helpers/helper-translation-discussion.php
- includes/class-gp-custom-locale-reasons.php
- includes/class-gp-translation-helpers.php
- js/reject-feedback.js
- templates/translation-row-editor-meta-feedback.php
Custom reasons have been requested for the `it` locale [here](https://make.wordpress.org/polyglots/2023/02/16/feedback-tool-custom-reasons-for-it_it/) 
In this PR we have added the custom reasons. However we noticed that the because some of the custom reasons had long texts, it distorted the view as shown below;
> Before
> After 
In this PR, we have also ensured that the custom reasons are nicely wrapped and properly displayed.
> Add custom reasons for `it` locale

- helpers/helper-translation-discussion.php
Comments are invisible because the post cannot be found after a temporary post id has been cached. The cache is not updated because `wp_cache_add()` was used which doesn't overwrite cache entries.
Use `wp_cache_set()` and remove that the cache fail workaround is only active when the page needs to be created.
This is hard to test since it relies on a cache that has the wrong value in production.
Fixes #165.
> Fix caching bug in translate.wordpress.org production

- css/discussion.css
- templates/translation-row-editor-meta-feedback.php
ChatGPT review box grows increasingly as the content is being streamed which affects the user experience of translation editors.
Wrap the ChatGPT review section in a `<details>`element, so that users can choose to collapse or reveal the ChatGPT review section
> Wrap ChatGPT review section in <details> element

- templates/translation-row-editor-meta-feedback.php
On clicking the details tag, an error is thrown by the editor.js file
Add missing class names to `<details>` tag
> Add class to details tag to fix js error

- includes/class-gp-translation-helpers.php
- js/editor.js
Users cannot enable or disable ChatGPT review.
When the user collapses the ChatGPT review (see https://github.com/GlotPress/gp-translation-helpers/pull/174), we should no longer query it.
1. Go to a translation page with waiting or fuzzy strings where you can approve strings.
2. When the ChatGPT review details view is open, ChatGPT should be queried.
3. When you close that details view and go to the next waiting translation, ChatGPT should not be queried.
4. When you now open the review details view, ChatGPT should be queried for that current translation.
5. Close that view again.
6. Reload the page.
7. The ChatGPT review details view should remain closed when opening a waiting string, nothing should be queried.
> Check if ChatGPT review is enabled by user

- js/editor.js
When you want to start translating, and you open the first row, an AJAX query is fired to get the translation helpers. This query needs some time to be transmitted and showed, so you don't see the content immediately. 
This PR adds a local cache for the translation helpers, in 1 local variable:
* For the first row when the page loads, so when the user opens the first row, she gets the translation helpers immediately.
* For the next row, when she opens a row, so when the user opens the next row, she gets the translation helpers immediately.
We only cache what we believe to be the most likely row to be opened next, not all of them, as this avoids making excessive AJAX calls. 
I suggest to made, at least, 2 tests with:
* a table with a few strings to translate. You need to review that we …
> Preload the translation helpers

- helpers-assets/templates/translation-discussion-comments.php
When the system doesn't have a user logged, it shows the next error in the JavaScript console when we are in a page with a list of strings. It is independent of the translation state of these strings.
Reported by @psmits1567 [here](https://github.com/GlotPress/gp-translation-helpers/pull/113#issuecomment-1637481800). 
The problem is happening at DotOrg because the system doesn't load the `mentions` file if the user is not logged.
Without a logged user:
With a logged user:
Load a list of strings in a project and take a look at the JavaScript console, to see that now you don't see the error message.
> Check if the mentions function exists

- helpers/helper-other-locales.php
The plugin doesn't have the related locales to Occitan.
Solves https://github.com/GlotPress/gp-translation-helpers/issues/188.
This PR adds an array with the related locales to Occitan.
> Add the related locales to Occitan

- helpers/helper-other-locales.php
The plugin doesn't have the related locales to Catalan.
Fixes https://github.com/GlotPress/gp-translation-helpers/issues/191.
This PR adds an array with the related locales to Catalan.
> Add the related locales to Catalan

- includes/class-gp-route-translation-helpers.php
This plugin has [2 endpoints](https://github.com/GlotPress/gp-translation-helpers/blob/c012fdf90b0f3dd984553fdb4b851bf9a67dabe6/includes/class-gp-translation-helpers.php#L336-L337) who response with AJAX content, but their `Content-Type` is `text/html`, so when you access with a web browser, the content is bad-formatted.
Fixes https://github.com/GlotPress/gp-translation-helpers/issues/182.
Props @Presskopp
This PR changes the `Content-Type` from `text/html` to `application/json`, so the content type is the correct and is well-formatted as JSON in the web browser.
If you use some JSON viewer browser plugin (e.g. [JSONVue](https://github.com/gildas-lormeau/JSONVue)), you can see it is well-formatted.
> Change the returned Content-Type from text/html to application/json

- includes/class-gp-route-translation-helpers.php
With PHP 8.0, I get this error:
`Deprecated: usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /wordpress/glotpress/wp-content/plugins/gp-translation-helpers/includes/class-gp-route-translation-helpers.php on line 234`
This is the same problem that this one https://github.com/GlotPress/GlotPress/pull/1464.
Fixes https://github.com/GlotPress/gp-translation-helpers/issues/194.
Change the `>` operator to the `<=>` operator into the usort user-defined comparison function.
> Fixes deprecation notice in PHP8 for usort returning bool

- helpers/helper-other-locales.php
The plugin doesn't have the related locales to Italian.
[Fixes https://github.com/GlotPress/gp-translation-helpers/issues/191](https://github.com/GlotPress/gp-translation-helpers/issues/196).
This PR adds an array with the related locales to Italian.
> Add the related locales to Italian

- helpers/helper-other-locales.php
The plugin doesn't have the related locales to Uighur.
Fixes https://github.com/GlotPress/gp-translation-helpers/issues/201.
Proposed by [Nureli Tashpolat](https://profiles.wordpress.org/sepra/) (@Nureli-Tashpolat), who is a [Uighur LM and GTE](https://make.wordpress.org/polyglots/teams/?locale=ug_CN).
This PR adds an array with the related locales to Uighur.
> Add the related locales to Uighur

- composer.lock
- templates/translation-row-editor-meta-feedback.php
Errors are thrown because the `for` attribute for a label cannot find a field with same `id`. 
See trac ticket --> https://meta.trac.wordpress.org/ticket/7348
Add a matching `id` and `for` attribute.
Navigate to the waiting strings page of a project, for example - https://translate.wordpress.org/projects/wp-plugins/events-manager/dev/art-xemoji/default/?filters%5Bstatus%5D=waiting
Open the browser console, you would find the error
> Fix console errors due to label `for` attribute

- includes/class-wporg-notifications.php
> Fix return type error

- css/discussion.css
- css/editor.css
- js/editor.js
- templates/gp-templates-overrides/translation-row-editor-meta.php
Currently, we have 4 tabs in the right sidebar to show different information:
- Meta.
- Discuss.
- History.
- Other locales.
At [translate.wordpress.org](https://translate.wordpress.org/) we have added a fifth tab with the translation memory:
These tabs take up a lot of horizontal space with small devices and/or screens, showing tabs with only a few letters and without the number of elements, with a bad usability.
This PR merges the content from the "History" and "Other locales" in a new tab, called "Others", removing the two previous tabs.
This PR adds "summary" elements, so the user could show or hide the different elements. This PR doesn't remember the status of each summary (opened or closed).
To test this PR you have to access to a project with some locales and translations in the …
> Add a new tab to merge the "History" and "Other locales" tabs

- helpers/helper-translation-discussion.php
Some WordPress GTE have requested to add a new AI option to the "Give feedback" checkboxes.
This PR adds this new checkbox.
When you use this checkbox (and, optionally, the comment)
You get a new comment with the AI reason
Fixes https://github.com/GlotPress/gp-translation-helpers/issues/214.
> Add a new AI checkbox to the "Give feedback" section

- js/editor.js
When a user hides the "ChatGPT Review" element, next time she reloads the page and tries to see this element, it is hidden, due to an incorrect check. 
This PR updates the logic to show the different elements:
- First check:
- Checks if `openai_key` is not present.
- Checks if the user cannot approve.
- Checks if the translation status is neither `waiting` nor `fuzzy`.
If any of these conditions are true, "ChatGPT Review" is hidden (`.details-chatgpt`).
- Second check (If none of the previous conditions are true):
- Checks if `chatgpt_review_enabled` is false. If this condition is true, only the "Review by ChatGPT" (`.openai-review`) element is hidden, not the "ChatGPT Review" title.
- Final else Block: If all conditions are met (i.e., `chatgpt_review_enabled` is true, we have …
> Resolve a bug when the user hides the "ChatGPT Review" element

- js/reject-feedback.js
When we process a bulk update, the selected checkboxes in the bulk form are deselected. This affects to another plugins, like the new [WPORG GP Bulk pre-translations](https://github.com/amieiro/wporg-gp-bulk-pretranslations) plugin.
This PR removes this uncheck. I have manually tested it and doesn't affect the bulk rejection.
To test it, make some bulk approvals and rejections and you will see all works fine.
> Do not uncheck the bulk checkboxes

- includes/class-gp-translation-helpers.php
- js/editor.js
- js/translation-helpers.js
The GP Translation Helpers loads a non-slashed path, which is immediately redirected to the slashed variant by redirect_canonical().
Translate.wordpress.org has a low requests-per-second limit, and this results in double the number of XHR requests being made than required.
Use a slashed link.
Because of how the links are generated, I chose to use an interpolated template instead of simply adding `/` to the links.
I also removed the `?nohc` from the URLs as I couldn't see any reason for them - Other than that it allowed a specific use case to simply append with `&...` which is all I can imagine it was for.
**Before**
**After**
> Use a XHR link that has a trailing slash on it, to avoid 302's that eat into the request budget
